server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.bms.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rocketmq:
  name-server: localhost:9876
  producer:
    group: bms-producer-group
  consumer:
    group: bms-consumer-group
  topic: bms-signal
#  .\bin\mqnamesrv
#  .\bin\mqbroker -n localhost:9876